CREATE DEFINER=`root`@`localhost` PROCEDURE `insertBankinfo`(CID INT, CIBAN VARCHAR(255), CBIC VARCHAR(255), CKreditNr INT, CKreditcode INT)
BEGIN
INSERT INTO BankInformation 
VALUES(CID, AES_ENCRYPT(CONCAT(CIBAN,CID), "123Test"),AES_ENCRYPT(CONCAT(CBIC,CID), "123Test"),AES_ENCRYPT(CONCAT(CIBAN,CID), "123Test"),
		AES_ENCRYPT(CONCAT(CKreditNr,CID), "123Test"),AES_ENCRYPT(CONCAT(CKreditcode,CID), "123Test"));
END